language: go


env:
  - DEP_VERSION=0.5.0

services:
  - docker

# before_install:                                                                 
#   - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  

go:
  - 1.12.x

ignore:
  - python/*
  - test/*

script:
- go version
- echo $GOPATH
- pwd
- CGO_ENABLED=0 go build -tags netgo -a -v -o spider ./go/src
- docker build -f go/Dockerfile -t amanohikaru/spider .
- docker login -u amanohikaru -p cao12345
- docker push amanohikaru/spider

