language: go


env:
  - DEP_VERSION=0.5.0

services:
  - docker

# before_install:                                                                 
#   - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  

go:
  - 1.12.x

script:
- echo $GOPATH
- echo $TRAVIS_BRANCH
- docker build -f python/Dockerfile -t lin1heart/dingdian .
- docker login -u $DOCKER_USER_LIN -p $DOCKER_PASS_LIN
- docker push lin1heart/dingdian
- curl -X POST http://util.online:9000/api/webhooks/2e134b95-28b2-4598-8bcc-4d5f3384d045

