language: go


env:
  - DEP_VERSION=0.5.0

services:
  - docker

# before_install:                                                                 
#   - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh  

go:
  - 1.12.x

ignore:
  - python/*
  - test/*

script:
- go version
- echo $GOPATH
- pwd
- go build -o spider ./go/src

