
version: "3.5"

networks:
  n1:
    external: true

services:
  python:
    image: "lin1heart/dingdian"
    command: python dingdian.py
    networks:
    - n1
  push:
    image: "lin1heart/dingdian"
    command: python push.py
    networks:
    - n1
